version: '3.8'
services:
  django_backend:
    build: ./django_backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  email_worker:
    build: ./email-worker
    environment:
      - SENDER_MAIL=micaelgomestargino@gmail.com
      - SENDER_PASSWORD=qdlf mfqw brae lupz
      - REDIS_HOST=redis
      - SUPABASE_URL=https://dndnbfmacguvntfxqvop.supabase.co
      - SUPABASE_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuZG5iZm1hY2d1dm50Znhxdm9wIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwNDA2MDIzNCwiZXhwIjoyMDE5NjM2MjM0fQ.XSzmPuc1c0SA56gdqVsNHv8Gvv83xf7weKVYW9RHJqM
    depends_on:
      - redis

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REQUEST_URL='http://django_backend:8000'

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
