# Generated by Django 4.2.8 on 2024-01-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
